ERROR - 2024-06-03 08:03:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: YES) in C:\xampp\htdocs\pbo--app\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\pbo--app\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'warung_bagas', 3306, '', 0)
#1 C:\xampp\htdocs\pbo--app\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\pbo--app\system\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\pbo--app\system\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#4 C:\xampp\htdocs\pbo--app\system\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(NULL)
#5 C:\xampp\htdocs\pbo--app\system\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#6 C:\xampp\htdocs\pbo--app\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#7 C:\xampp\htdocs\pbo--app\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', Array)
#8 C:\xampp\htdocs\pbo--app\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#9 C:\xampp\htdocs\pbo--app\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#10 C:\xampp\htdocs\pbo--app\spark(83): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: YES) in C:\xampp\htdocs\pbo--app\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\pbo--app\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\pbo--app\system\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\pbo--app\system\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#3 C:\xampp\htdocs\pbo--app\system\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(NULL)
#4 C:\xampp\htdocs\pbo--app\system\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#5 C:\xampp\htdocs\pbo--app\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#6 C:\xampp\htdocs\pbo--app\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', Array)
#7 C:\xampp\htdocs\pbo--app\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\pbo--app\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\pbo--app\spark(83): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}
CRITICAL - 2024-06-03 08:03:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: YES)
[Method: CLI, Route: db:seed/UserSeeder]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
 3 SYSTEMPATH\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(null)
 4 SYSTEMPATH\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
 5 SYSTEMPATH\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run([...])
 6 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', [...])
 7 SYSTEMPATH\Boot.php(338): CodeIgniter\CLI\Console->run()
 8 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
 9 ROOTPATH\spark(83): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
